In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv("heart.csv")

In [4]:
data.head(5)

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [5]:
data.tail(5)

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [6]:
le = LabelEncoder()
# labels = le.fit_transform(data['AHD'])
chestpain = le.fit_transform(data['ChestPain'])
thal = le.fit_transform(data['Thal'])
le.classes_

array(['fixed', 'normal', 'reversable', nan], dtype=object)

In [7]:
# data['AHD'] = labels
data['ChestPain'] = chestpain
data['Thal'] =thal
data = data.drop(columns = 'Ca', axis = 1)
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0,No
1,2,67,1,0,160,286,0,2,108,1,1.5,2,1,Yes
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2,Yes
3,4,37,1,1,130,250,0,0,187,0,3.5,3,1,No
4,5,41,0,2,130,204,0,2,172,0,1.4,1,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,2,Yes
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2,Yes
300,301,57,1,0,130,131,0,0,115,1,1.2,2,2,Yes
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1,Yes
302,303,38,1,1,138,175,0,0,173,0,0.0,1,1,No

In [8]:
data['AHD'].value_counts()

No     164
Yes    139
Name: AHD, dtype: int64

In [9]:
X = data.drop(columns="AHD", axis=1)
Y = data['AHD']

In [10]:
X.head(2)

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Thal
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,1

In [11]:
Y.head(3)

0     No
1    Yes
2    Yes
Name: AHD, dtype: object

In [12]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y, test_size=0.6, stratify=Y,random_state=2)

In [13]:
model = LogisticRegression()
model.fit(X_train,Y_train)
prediction = model.predict(X_test)
accuracy = accuracy_score(prediction,Y_test)
accuracy

C:\Users\hp\anaconda3\envs\tensorflow-env\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7912087912087912

In [14]:
# model = DecisionTreeClassifier()
# model.fit(X_train,Y_train)
# prediction = model.predict(X_test)
# accuracy = accuracy_score(prediction,Y_test)
# accuracy

In [15]:
# model = RandomForestClassifier()
# model.fit(X_train,Y_train)
# prediction = model.predict(X_test)
# accuracy = accuracy_score(prediction,Y_test)
# accuracy

In [16]:
# model = KNeighborsClassifier()
# model.fit(X_train,Y_train)
# prediction = model.predict(X_test)
# accuracy = accuracy_score(prediction,Y_test)
# accuracy

In [17]:
input_data =(1,63,1,3,145,233,1,2,150,0,2.3,3,0)
input_data_array = np.asarray(input_data)
reshaped_input = input_data_array.reshape(1,-1)

In [18]:
pred = model.predict(reshaped_input)
if (pred[0] == "Yes"):
    print("you have a heart disease")
else:
        print("you are healthy")

you are healthy

C:\Users\hp\anaconda3\envs\tensorflow-env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [26]:
# import gradio as gr

In [ ]:
# def classify(inp):
#     input_data_array = np.asarray(inp)
#     reshaped_input = input_data_array.reshape(1,-1)
#     pred = model.predict(reshaped_input)
#     return pred

In [30]:
# iface = gr.Interface(fn=classify,inputs= "number",outputs="text").launch()

Socket exception: An existing connection was forcibly closed by the remote host (10054)
Socket exception: An existing connection was forcibly closed by the remote host (10054)
Socket exception: An existing connection was forcibly closed by the remote host (10054)